#!/usr/bin/env python3
"""main.cpp renderer for the VPTO onboard host (path-neutralized, onboard-only).

Vendored and trimmed from test_for_ptoas/setup_main.py. Only the onboard
main.cpp generator is kept (no camodel, no dlopen — onboard links the kernel
.so directly via `-l<kernel>_kernel`). The template is the canonical host
program: it reads `*.bin` inputs, allocates device memory, launches the
kernel, copies outputs back, and writes `*.bin`.

This module has no CLI; `vpto_run.py` imports `gen_main_cpp()` from it.
"""

from __future__ import annotations

from .pto_parse import parse_pto, pto_type_to_c, PTO_TO_CPP, get_outputs_from_golden_lib, get_golden_constants, get_scalar_semantic_names, compute_scalar_comment


_MAIN_TEMPLATE_ONBOARD = """\
// Auto-generated by the vpto-board-validate skill (main.cpp renderer)
#include "test_common.h"
#include "acl/acl.h"
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fstream>

// host-side bfloat16_t compatibility
typedef uint16_t bfloat16_t;

using namespace PtoTestCommon;

#ifndef TMRGSORT_HPP
namespace pto { struct MrgSortExecutedNumList {
    uint16_t mrgSortList0, mrgSortList1, mrgSortList2, mrgSortList3;
}; } // namespace pto
#endif

// -- 3-arg ReadFile/WriteFile wrappers (pto-isa test_common.h uses 4-arg) --
namespace {
bool ReadFile3(const std::string &path, void *buffer, size_t size) {
    size_t fileSize = 0;
    return ReadFile(path, fileSize, buffer, size) && fileSize == size;
}
bool WriteFile3(const std::string &path, const void *buffer, size_t size) {
    std::ofstream file(path, std::ios::binary | std::ios::trunc);
    if (!file.is_open()) return false;
    file.write(static_cast<const char *>(buffer), size);
    return file.good();
}
}  // namespace

#define ACL_CHECK(expr) do {                                              \\
    const aclError _ret = (expr);                                         \\
    if (_ret != ACL_SUCCESS) {                                            \\
        std::fprintf(stderr, "[ERROR] %s failed: %d (%s:%d)\\n",           \\
                     #expr, (int)_ret, __FILE__, __LINE__);               \\
        const char *_recent = aclGetRecentErrMsg();                        \\
        if (_recent != nullptr && _recent[0] != '\\0')                     \\
            std::fprintf(stderr, "[ERROR] RecentErrMsg: %s\\n", _recent);  \\
        rc = 1; goto cleanup;                                             \\
    }                                                                     \\
} while (0)

@LAUNCH_DECL@

int main() {
@PARAM_DECLS@
@PTR_DECLS@

    int rc = 0;
    bool aclInited = false, deviceSet = false;
    int deviceId = 0;
    aclrtStream stream = nullptr;

    ACL_CHECK(aclInit(nullptr)); aclInited = true;
    if (const char *env = std::getenv("ACL_DEVICE_ID")) deviceId = std::atoi(env);
    ACL_CHECK(aclrtSetDevice(deviceId)); deviceSet = true;
    ACL_CHECK(aclrtCreateStream(&stream));

@ALLOC_HOST@
@ALLOC_DEVICE@
@READ_INPUTS@
@COPY_TO_DEVICE@
    {
        auto _t0 = std::chrono::high_resolution_clock::now();
@LAUNCH_CALL@
        ACL_CHECK(aclrtSynchronizeStream(stream));
        auto _t1 = std::chrono::high_resolution_clock::now();
        double _kernel_ms = std::chrono::duration<double, std::milli>(_t1 - _t0).count();
        std::printf("[TIMING] kernel=@KERNEL_NAME@ time=%.3f ms\\n", _kernel_ms);
    }
@COPY_BACK@
@WRITE_OUTPUTS@

cleanup:
@FREE_DEVICE@
@FREE_HOST@
    if (stream) aclrtDestroyStream(stream);
    if (deviceSet) aclrtResetDevice(deviceId);
    if (aclInited) aclFinalize();
    return rc;
}
"""


def gen_main_cpp(info: dict, outputs: list, load_vals: dict | None = None,
                 consts: dict | None = None, scalar_sem_names: list | None = None,
                 elem_counts_override: dict | None = None) -> str:
    """Render the onboard main.cpp from the .pto's parsed info.

    `info` is parse_pto()'s output. `outputs` is the list of output buffer
    names (from the golden_lib's BUILDERS return). `load_vals`/`consts`/
    `scalar_sem_names` fill ctx_len/ctx_blocks when the golden_lib exposes
    them; other scalars get `// FIXME` comments.

    `elem_counts_override` (Mode B): {vN: int} from the model's TensorSpec
    shape product — used when the .pto has dynamic shapes (e.g. [%arg3, D])
    that parse_pto can't reduce to a static count. Falls back to
    info["elem_counts"] when not given.
    """
    func = info["func_name"]
    launch = func[0].upper() + func[1:]
    ptrs = [p for p in info["params"] if p["pto_type"] not in ("i32", "index")]
    scals = [p for p in info["params"] if p["pto_type"] in ("i32", "index")]
    ec = dict(info.get("elem_counts", {}))
    if elem_counts_override:
        ec.update(elem_counts_override)
    output_set = set(outputs)
    load_vals = load_vals or {}
    consts = consts or {}
    scalar_sem_names = scalar_sem_names or []

    def cpp_type(name):
        for p in info["params"]:
            if p["name"] == name:
                return PTO_TO_CPP.get(p["pto_type"], "float")
        return "float"

    param_decls, ptr_decls = [], []
    alloc_host, alloc_dev = [], []
    free_host, free_dev = [], []
    reads, copy_in, copy_out, writes = [], [], [], []

    for p in ptrs:
        n, ct = p["name"], cpp_type(p["name"])
        e = ec.get(n, 0)
        param_decls.append(f"    size_t elemCount_{n} = {e};" +
                           ("" if e else "  // skipped: 0-elem (dynamic shape)"))
        param_decls.append(f"    size_t fileSize_{n} = elemCount_{n} * sizeof({ct});")
        ptr_decls.append(f"    {ct} *{n}Host = nullptr;")
        ptr_decls.append(f"    {ct} *{n}Device = nullptr;")
        if not e:
            # C4: a 0-elem ptr (dynamic shape whose numel wasn't captured, or a
            # genuinely empty output) would make aclrtMallocHost/Malloc fail on
            # size=0 (ACL 100000 / EH0007) and ReadFile3 fail on a 0-byte file.
            # Skip alloc/read/copy/free for it — both Host/Device stay nullptr
            # and the kernel receives a null GM ptr (single-block launch never
            # touches it under 0-elem). This unblocks kernels that crash at
            # the alloc stage before reaching the real precision test.
            continue
        alloc_host.append(f"    ACL_CHECK(aclrtMallocHost((void **)(&{n}Host), fileSize_{n}));")
        alloc_dev.append(f"    ACL_CHECK(aclrtMalloc((void **)&{n}Device, fileSize_{n}, ACL_MEM_MALLOC_HUGE_FIRST));")
        free_dev.append(f"    aclrtFree({n}Device);")
        free_host.append(f"    aclrtFreeHost({n}Host);")
        reads.append(f'    if (!ReadFile3("./{n}.bin", {n}Host, fileSize_{n}))'
                     f' {{ std::fprintf(stderr, "Failed to read {n}.bin\\n"); rc = 1; goto cleanup; }}')
        copy_in.append(f"    ACL_CHECK(aclrtMemcpy({n}Device, fileSize_{n}, {n}Host, fileSize_{n}, ACL_MEMCPY_HOST_TO_DEVICE));")
        if n in output_set:
            copy_out.append(f"    ACL_CHECK(aclrtMemcpy({n}Host, fileSize_{n}, {n}Device, fileSize_{n}, ACL_MEMCPY_DEVICE_TO_HOST));")
            writes.append(f'    if (!WriteFile3("./{n}.bin", {n}Host, fileSize_{n}))'
                          f' {{ std::fprintf(stderr, "Failed to write {n}.bin\\n"); rc = 1; }}')

    for i, s in enumerate(scals):
        sem = scalar_sem_names[i] if i < len(scalar_sem_names) else None
        hint = compute_scalar_comment(sem, consts, load_vals, s.get("sig_name", ""))
        scal_type = pto_type_to_c(s.get("pto_type", "i32"))[0]
        if sem == "ctx_len" and load_vals.get("ctx_len") is not None:
            param_decls.append(f"    {scal_type} {s['name']} = {load_vals['ctx_len']};  // {hint}")
        elif sem == "ctx_blocks" and load_vals.get("ctx_blocks") is not None:
            param_decls.append(f"    {scal_type} {s['name']} = {load_vals['ctx_blocks']};  // {hint}")
        elif sem == "derived" and s["name"] in (load_vals.get("derived") or {}):
            # Value recovered from a .pto tensor-view shape: the scalar
            # controls a single dynamic tensor dimension, so its value =
            # elem_count // product(other static dims). See
            # pto_parse.derive_scalar_values.
            v = load_vals["derived"][s["name"]]
            param_decls.append(f"    {scal_type} {s['name']} = {v};  // {hint}")
        elif sem == "dumped" and s["name"] in (load_vals.get("dumped") or {}):
            # Runtime value captured in args_dump.json (the scalar's `value`
            # field from the Route-1 dump, written to capture_meta.json by
            # harvest_kernel). Used for scalars not derivable from shapes,
            # e.g. partition_view offsets such as mtp_projection_rms %arg4.
            v = load_vals["dumped"][s["name"]]
            param_decls.append(f"    {scal_type} {s['name']} = {v};  // {hint}")
        else:
            # SPMD block_num must be 1 for a single-block launch (0 means "no
            # blocks" → the kernel body never runs → all-zero output). block_idx
            # stays 0. Everything else defaults to 0 (FIXME: needs golden-lib
            # semantics or a per-op scalar map).
            sig = s.get("sig_name", "") or s.get("name", "")
            if "spmd_block_num" in sig:
                param_decls.append(f"    {scal_type} {s['name']} = 1;  // {hint}")
            else:
                param_decls.append(f"    {scal_type} {s['name']} = 0;  // FIXME: {hint}")

    decl_parts, call_parts = [], []
    for p in info["params"]:
        n, ct = p["name"], cpp_type(p["name"])
        if p["pto_type"] in ("i32", "index"):
            scal_type = pto_type_to_c(p["pto_type"])[0]
            decl_parts.append(f"{scal_type} {n}"); call_parts.append(n)
        else:
            decl_parts.append(f"{ct} *{n}"); call_parts.append(f"{n}Device")
    launch_decl = f"void Launch{launch}({', '.join(decl_parts)}, void *stream);"
    launch_call = f"    Launch{launch}({', '.join(call_parts)}, stream);"

    return (_MAIN_TEMPLATE_ONBOARD
            .replace("@LAUNCH_DECL@", launch_decl)
            .replace("@PARAM_DECLS@", "\n".join(param_decls))
            .replace("@PTR_DECLS@", "\n".join(ptr_decls))
            .replace("@ALLOC_HOST@", "\n".join(alloc_host))
            .replace("@ALLOC_DEVICE@", "\n".join(alloc_dev))
            .replace("@READ_INPUTS@", "\n".join(reads))
            .replace("@COPY_TO_DEVICE@", "\n".join(copy_in))
            .replace("@LAUNCH_CALL@", launch_call)
            .replace("@COPY_BACK@", "\n".join(copy_out))
            .replace("@WRITE_OUTPUTS@", "\n".join(writes))
            .replace("@FREE_DEVICE@", "\n".join(free_dev))
            .replace("@FREE_HOST@", "\n".join(free_host))
            .replace("@KERNEL_NAME@", func))
