#!/usr/bin/env python3
"""VPTO onboard test-scaffold generator (path-neutralized, onboard-only).

Vendored and trimmed from the test_for_ptoas harness (which supports onboard
+ camodel-docker + camodel-remote). This module keeps only the **onboard real-NPU**
path: it generates the `launch.cpp` wrapper and the `run.sh` orchestration for a
single kernel's VPTO board run.

All paths come from environment variables (PTOAS_BIN, ASCEND_HOME_PATH,
PTO_ISA_PATH, TILELANG_PATH, TILELANG_PKG, BISHENG_BIN, DEVICE_ID). No host
paths are hardcoded, so this works on any machine whose env is set up by
`scripts/vpto_env.sh` (or the equivalent env vars exported by the caller).

The ptoas compile options (the three fusion flags + level3 + a5) are the
**proven-working** set for lowering pypto EmitC-era .pto through the VPTO
backend. Do NOT turn fusion off — that yields an empty ctor-only fatobj.
"""

from __future__ import annotations

import os
from pathlib import Path

from .pto_parse import parse_pto, pto_type_to_c

# PTOAS compile options (without input/output paths). The fusion flags MUST
# stay on — turning them off skips kernel codegen and emits a ctor-only fatobj.
PTO_COMPILE_OPT = [
    "--pto-arch=a5",
    "--pto-level=level3",
    "--pto-backend=vpto",
    "--enable-tile-op-expand",
    "--enable-insert-sync",
    "--enable-op-fusion",
]
PTO_COMPILE_OPT_STR = " ".join(PTO_COMPILE_OPT)

_LAUNCH_HEADER = r"""// ---------------------------------------------------------------------------
// PTOAS VPTO compatibility layer — auto-generated by the vpto-board-validate skill
// ---------------------------------------------------------------------------
#ifndef __VEC_SCOPE__
#define __VEC_SCOPE__
#endif

#if defined(__CCE_AICORE__) && defined(__NPU_ARCH__) && (__NPU_ARCH__ == 2201)
typedef struct { unsigned char v; } hifloat8_t;
typedef struct { unsigned char v; } float8_e4m3_t;
typedef struct { unsigned char v; } float8_e5m2_t;
typedef struct { unsigned char v; } float8_e8m0_t;
typedef struct { unsigned char v; } float4_e1m2x2_t;
typedef struct { unsigned char v; } float4_e2m1x2_t;
#endif
#include <stdint.h>

#if defined(__CCE_AICORE__) && defined(PTOAS_ENABLE_CCE_PRINT)
#include <ccelib/print/print.h>
#endif
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>

#if !defined(__CCE_AICORE__) && !defined(TMRGSORT_HPP)
namespace pto {
struct MrgSortExecutedNumList {
    uint16_t mrgSortList0, mrgSortList1, mrgSortList2, mrgSortList3;
};
} // namespace pto
#endif
#ifndef __CPU_SIM
#include "acl/acl.h"
#endif
"""


def detect_kernel_kind(pto_text: str) -> str:
    """Return 'cube' or 'vector' by grepping the .pto's kernel_kind attribute."""
    return "cube" if "kernel_kind" in pto_text and "cube" in pto_text else "vector"


def preprocess_pto(pto_src: Path, pto_dst: Path, kernel_kind: str) -> None:
    """Apply the two mandatory sed edits that tell ptoas to emit the kernel body.

    Without these, ptoas VPTO silently emits a ctor-only fatobj (no kernel
    symbol) — the failure mode that was previously misdiagnosed as a dialect
    mismatch. The two edits:
      1. module: add `pto.kernel_kind = #pto.kernel_kind<${kind}>` (no-op if
         the .pto already carries it, e.g. Qwen3 rmsnorm.pto).
      2. func:    `attributes {pto.kernel_kind` → `attributes {pto.kernel, pto.kernel_kind`
         (adds the `pto.kernel` attr that triggers kernel codegen).
    """
    text = pto_src.read_text(encoding="utf-8")
    text = text.replace(
        'module attributes {pto.target_arch = "a5"}',
        f'module attributes {{pto.target_arch = "a5", pto.kernel_kind = #pto.kernel_kind<{kernel_kind}>}}',
    )
    text = text.replace(
        "attributes {pto.kernel_kind",
        "attributes {pto.kernel, pto.kernel_kind",
    )
    pto_dst.write_text(text, encoding="utf-8")


def generate_launch_cpp(info: dict) -> str:
    """Generate the launch.cpp wrapper: `void Launch<Func>(..., void*stream)`
    that calls `func<<<1, nullptr, stream>>>(...)`. Grid is always 1 — the
    spmd block_idx/block_num are passed as scalar args from the host main.cpp."""
    func_name = info["func_name"]
    launch_name = func_name[0].upper() + func_name[1:]

    gm_parts, host_parts, call_parts = [], [], []
    for p in info["params"]:
        c_type, gm_type = pto_type_to_c(p["pto_type"])
        if p["pto_type"] in ("i32", "index"):
            gm_parts.append(f"{c_type} {p['name']}")
            host_parts.append(f"{c_type} {p['name']}")
            call_parts.append(p["name"])
        else:
            gm_parts.append(f"{gm_type} {p['name']}")
            host_parts.append(f"{c_type} *{p['name']}")
            call_parts.append(f"({gm_type}){p['name']}")

    body = f"""
extern "C" __global__ AICORE void {func_name}({', '.join(gm_parts)});

void Launch{launch_name}({', '.join(host_parts)}, void *stream) {{
    {func_name}<<<1, nullptr, stream>>>({', '.join(call_parts)});
}}
"""
    return _LAUNCH_HEADER + body


def generate_run_sh(kernel: str, build_dir: Path, sample_dir: Path) -> str:
    """Generate run.sh for the onboard VPTO run. Mirrors the test_for_ptoas
    _RUN_ONBOARD template but is parameterized (no KERNEL over-replace bug)."""
    ptoas_bin = "${PTOAS_BIN}"
    ascend = "${ASCEND_HOME_PATH}"
    bisheng = "${BISHENG_BIN}"
    pto_isa = "${PTO_ISA_PATH}"
    tilelang = "${TILELANG_PATH}"
    tilelang_pkg = "${TILELANG_PKG}"
    device = "${DEVICE_ID:-0}"
    return f"""#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by the vpto-board-validate skill. Onboard VPTO run.
# Requires env: PTOAS_BIN, ASCEND_HOME_PATH, BISHENG_BIN, PTO_ISA_PATH,
# TILELANG_PATH, TILELANG_PKG, DEVICE_ID, and /tmp/mlir_core_vmi built
# (source scripts/vpto_env.sh first, or let vpto_run.py set it up).

ROOT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
BUILD_DIR="${build_dir}"
SAMPLE_DIR="${sample_dir}"
KERNEL_NAME="${kernel}"
PTO_SRC="${{SAMPLE_DIR}}/${{KERNEL_NAME}}.pto"
PTO_FILE="${{BUILD_DIR}}/${{KERNEL_NAME}}.pto"
FATOBJ="${{BUILD_DIR}}/${{KERNEL_NAME}}.o"

# Step 1: golden
echo "=== Step 1/4: golden ==="
python3 "${{ROOT_DIR}}/golden.py"

# Step 2: ptoas VPTO -> fatobj
echo "=== Step 2/4: ptoas VPTO .pto -> fatobj .o ==="
KERNEL_KIND=$(grep -q 'kernel_kind.*cube' "${{PTO_SRC}}" && echo cube || echo vector)
sed -e "s|module attributes {{pto.target_arch = \\"a5\\"}}|module attributes {{pto.target_arch = \\"a5\\", pto.kernel_kind = #pto.kernel_kind<${{KERNEL_KIND}}>}}|" \\
    -e 's/attributes {{pto.kernel_kind/attributes {{pto.kernel, pto.kernel_kind/' \\
    "${{PTO_SRC}}" > "${{PTO_FILE}}"

PYTHONPATH="/tmp/mlir_core_vmi:${{PYTHONPATH_OVERRIDE:-}}:${{TILELANG_PKG}}" \\
PTO_ISA_PATH="${{PTO_ISA_PATH}}" \\
ASCEND_HOME_PATH="${{ASCEND_HOME_PATH}}" \\
  "${{PTOAS_BIN}}" \\
    {PTO_COMPILE_OPT_STR} \\
    --tilelang-path "${{TILELANG_PATH}}" \\
    --tilelang-pkg-path "${{TILELANG_PKG}}" \\
    "${{PTO_FILE}}" -o "${{FATOBJ}}"
[[ -f "${{FATOBJ}}" ]] || {{ echo "ERROR: ptoas failed to produce fatobj" >&2; exit 1; }}

# Step 3: bisheng compile + link
echo "=== Step 3/4: bisheng compile launch + link .so + compile main ==="
"${{BISHENG_BIN}}" -c -fPIC -xcce -fenable-matrix --cce-aicore-enable-tl \\
  -fPIC -Xhost-start -Xhost-end \\
  -mllvm -cce-aicore-stack-size=0x8000 -mllvm -cce-aicore-function-stack-size=0x8000 \\
  -mllvm -cce-aicore-record-overflow=true -mllvm -cce-aicore-addr-transform \\
  -mllvm -cce-aicore-dcci-insert-for-scalar=false \\
  --cce-aicore-arch=dav-c310-vec -DREGISTER_BASE -std=c++17 \\
  -Wno-macro-redefined -Wno-ignored-attributes \\
  -I "${{ASCEND_HOME_PATH}}/include" -I "${{ASCEND_HOME_PATH}}/pkg_inc" \\
  -I "${{ASCEND_HOME_PATH}}/pkg_inc/profiling" -I "${{ASCEND_HOME_PATH}}/pkg_inc/runtime/runtime" \\
  -I "${{PTO_ISA_PATH}}/include" -I "${{PTO_ISA_PATH}}/tests/common" \\
  "${{ROOT_DIR}}/launch.cpp" -o "${{BUILD_DIR}}/launch.o"

"${{BISHENG_BIN}}" -fPIC -s -Wl,-z,relro -Wl,-z,now --cce-fatobj-link \\
  -shared -Wl,-soname,lib${{KERNEL_NAME}}_kernel.so \\
  -L "${{ASCEND_HOME_PATH}}/lib64" -Wl,-rpath,"${{ASCEND_HOME_PATH}}/lib64" \\
  -o "${{BUILD_DIR}}/lib${{KERNEL_NAME}}_kernel.so" \\
  "${{FATOBJ}}" "${{BUILD_DIR}}/launch.o" -Wl,--no-as-needed -lruntime

"${{BISHENG_BIN}}" -xc++ -include stdint.h -include stddef.h -std=c++17 \\
  "${{ROOT_DIR}}/main.cpp" \\
  -I "${{ASCEND_HOME_PATH}}/include" -I "${{PTO_ISA_PATH}}/include" -I "${{PTO_ISA_PATH}}/tests/common" \\
  -L "${{BUILD_DIR}}" -L "${{ASCEND_HOME_PATH}}/lib64" \\
  -Wl,-rpath,"${{BUILD_DIR}}" -Wl,-rpath,"${{ASCEND_HOME_PATH}}/lib64" \\
  -o "${{BUILD_DIR}}/${{KERNEL_NAME}}" -l${{KERNEL_NAME}}_kernel \\
  -Wl,--allow-shlib-undefined -Wl,--no-as-needed -lruntime \\
  -lstdc++ -lascendcl -lm -ltiling_api -lplatform -lc_sec -ldl -lnnopbase

# Step 4: NPU run + compare
echo "=== Step 4/4: NPU run (device ${{DEVICE_ID:-0}}) ==="
ACL_DEVICE_ID="${{DEVICE_ID:-0}}" \\
LD_LIBRARY_PATH="${{BUILD_DIR}}:${{ASCEND_HOME_PATH}}/lib64:${{LD_LIBRARY_PATH:-}}" \\
  "${{BUILD_DIR}}/${{KERNEL_NAME}}"
python3 "${{ROOT_DIR}}/compare.py"
"""
