#!/usr/bin/python3
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------
"""DSV4 VPTO self-contained golden references for the hc_pre / hc_post / hc_head
and gate / MoE-expert kernel families (24 split-out sub-kernels).

Each ``build_<name>(meta, generator, ints)`` mirrors a single ``.pto`` sub-kernel
whose signature lives in ``test_for_dsv4/kernel_signatures.json`` and whose host
main.cpp is generated by ``vpto_run.py``. The functions return
``(buffers_dict, golden_dict)`` where:

* ``buffers_dict`` maps the vN names from the .pto signature to numpy arrays of
  the element counts/dtypes that ``validation_runtime.load_case_meta`` parsed
  from main.cpp. Inputs are random (seeded); outputs are zero-initialized so the
  harness can detect writes the kernel performs. bf16 tensors are stored as
  uint16, matching the bf16 representation used by ``float32_to_bf16``.
* ``golden_dict`` maps the *output* vN names to the torch-computed expected
  values. The comparison harness writes these to ``golden_vN.bin`` and compares
  them against the device's written ``vN.bin``.

The math is a direct port of the torch ``golden_*`` references in the DSV4 model
files (``models/deepseek_v4_pro/{hc_pre,hc_post,hc_head,gate,expert_routed,
expert_shared}.py``), specialized to the decode (B=4, S=2 -> T=8) shapes the .pto
sub-kernels are compiled for. Where a sub-kernel writes only a *slice* of a
full-tensor output (e.g. hc_pre_linear atomic-adds into mixes_raw), the golden
returns the full expected tensor so every written lane is covered.
"""

import numpy as np

from validation_runtime import (
    bf16_to_float32,
    float32_to_bf16,
    rng,
    write_buffers,
    write_golden,
)

# --------------------------------------------------------------------------------------
# DSV4 PRO kernel constants (from models/deepseek_v4_pro/config.py PRO_KERNEL +
# the per-kernel tiling). These match the compile-time constants baked into the
# .pto files so the element counts / shapes agree.
# --------------------------------------------------------------------------------------
D = 7168                  # hidden_size
HC_MULT = 4               # hc_mult (hc stack width)
HC_DIM = HC_MULT * D      # 28672
MIX_HC = (2 + HC_MULT) * HC_MULT  # 24
MOE_INTER = 3072          # moe_intermediate_size
N_EXPERTS = 384           # n_routed_experts (full router space)
TOPK = 6                  # num_experts_per_tok
N_HASH_LAYERS = 3         # num_hash_layers
ROUTE_SCALE = 2.5         # routed_scaling_factor
VOCAB = 129280            # vocab_size
SWIGLU_LIMIT = 10.0       # swiglu_limit
NORM_EPS = 1e-6           # rms_norm_eps
HC_EPS = 1e-6             # hc_eps
HC_SINKHORN_ITER = 20     # hc_sinkhorn_iters
HC_DIM_INV = 1.0 / HC_DIM
INT8_SCALE_MAX = 127.0
INT8_AMAX_EPS = 1e-4
FP32_NEG_INF = -3.4028234663852886e38

# Decode shapes: the .pto sub-kernels are compiled for T = DECODE_BATCH*DECODE_SEQ
# = 4*2 = 8 tokens. ROUTE_SCORES_PAD = 512 (pad-expert row for sort32 + mrgsort).
T_DECODE = 8
T_PAD = 16                # gate pad (T_PAD = ceil(T/16)*16)
SCORE_PAD = 512           # padded expert row for sort
TOPK_PAD = 8              # TOPK padded to 32B-aligned width
# EP single-card routed layout: N_LOCAL_EXPERTS = N_EXPERTS // EP_WORLD_SIZE.
EP_WORLD_SIZE = 8
N_LOCAL_EXPERTS = N_EXPERTS // EP_WORLD_SIZE   # 48
RECV_MAX = EP_WORLD_SIZE * T_DECODE            # 64
# hc_pre/head layout pads (align tiles to 32B / 16-row cube rows).
MIX_PAD = 32              # MIX_HC (24) padded to a 32-wide cube N / vector row
HC_PAD = 8               # hc (4) padded for 32B-aligned vector ops
HC_HEAD_PAD = 16         # hc_head: HC_MULT (4) padded to 16-wide (head-only)
# Tiling constants referenced by the kernels (match .pto step constants).
RMS_K_CHUNK = 256        # hc_pre rms K-fragment
LINEAR_K_CHUNK = 256     # hc_pre linear cube K-fragment
HC_HEAD_RMS_K_CHUNK = 512
HC_HEAD_LINEAR_K_CHUNK = 256
QUANT_TILE = 256         # x_norm_quant / gate quant tile
GATE_D_TILE = 512        # gate K-loop D-fragment
K_TILE = 512             # routed/shared cube K-fragment
INTER_K = 512            # w2 K-fragment
MM_INTER_TILE = 256      # cube N-tile for gate/up matmul
ACT_INTER_TILE = 128     # routed activation N-tile
D_OUT_TILE = 256         # w2 cube D-tile
D_OUT_TILE_ACT = 512     # w2 dequant D-tile
SH_ACT_INTER_TILE = 1024
SH_QUANT_TILE = 1024
SH_D_OUT_TILE = 256
SH_D_OUT_TILE_ACT = 512


# --------------------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------------------
def _flat_output(meta, kernel: str, name: str) -> np.ndarray:
    """Allocate a zeroed output buffer sized to the kernel's parsed elem count.

    Some .pto sub-kernels declare an ``i32`` accumulator as a *ptr* (e.g.
    exp_w2_mm's v1 = [16, D] i32 output). ``parse_pto`` classifies any ``i32``
    param as a scalar and skips its elem_count, so ``meta.elem_counts`` has no
    entry for it. Dynamic-shape ptrs (shape ``[%argN, ...]``) are likewise
    absent. In those cases the per-kernel ``_OUTPUT_COUNTS`` fallback
    ("<kernel>:<vN>") supplies the model-derived numel so the golden is still
    correctly shaped; the dtype falls back to float32 when meta lacks it.
    """
    count = meta.elem_counts.get(name)
    if not count:
        count = _OUTPUT_COUNTS.get(f"{kernel}:{name}", 0)
    np_type = meta.np_types.get(name, np.float32)
    return np.zeros(count, dtype=np_type)


# Per-kernel fallback output element counts. Used when parse_pto could not
# reduce a buffer's shape to a static count (dynamic-shape ptrs whose dim is
# %argN, or i32-ptr accumulator outputs misclassified as scalars). Each value
# is the model-derived numel the build_ function's golden array is sized to.
# Keyed by "<kernel>:<vN>".
_OUTPUT_COUNTS = {
    # hc_pre: t_linear = T_PAD = 16 (decode 8 padded to 16-row cube tiles).
    "hc_pre_rms:v2":            T_DECODE,           # inv_rms [T,1]
    "hc_pre_seed:v1":           T_PAD * MIX_PAD,     # mixes_raw [t_linear, MIX_PAD]
    "hc_pre_linear:v3":         T_PAD * MIX_PAD,     # mixes_raw [t_linear, MIX_PAD]
    # hc_post: y [T, HC_MULT, D] flat.
    "hc_post:v1":               T_DECODE * HC_DIM,
    "hc_post_inactive_pad:v1":  T_DECODE * HC_DIM,   # decode y; inactive pad is a no-op at T
    "hc_post_prefill:v1":       128 * HC_DIM,        # prefill: 128 tokens
    # hc_head: T_MAX = 128 (max decode/prefill tokens).
    "hc_head_rms:v2":           128,                 # inv_rms [T_MAX,1]
    "hc_head_seed:v1":          128 * HC_HEAD_PAD,   # mixes_raw [T_MAX, HC_HEAD_PAD]
    "hc_head_linear:v3":        128 * HC_HEAD_PAD,   # mixes_raw [T_MAX, HC_HEAD_PAD]
    "hc_head_pre_fused:v3":     HC_HEAD_PAD * 128,   # pre_t [HC_HEAD_PAD, T_MAX]
    "hc_head_reduce:v2":        T_DECODE * D,         # y [T, D] bf16
    # gate / router.
    "ffn_norm:v3":              T_PAD * D,            # xg [T_PAD, D]
    "ffn_norm:v4":              T_PAD,                # inv_rms [T_PAD, 1]
    "ffn_norm:v5":              T_DECODE,             # x_norm_scale [T, 1]
    "ffn_norm:v6":              T_PAD,                # xn_scale [T_PAD, 1]
    "gate:v5":                  T_PAD * SCORE_PAD,    # route_scores [T_PAD, SCORE_PAD]
    "gate_pre_route:v1":       T_PAD * SCORE_PAD,    # biased_scores [T_PAD, SCORE_PAD]
    "route_hash:v4":            T_DECODE * TOPK,      # indices [T, TOPK]
    "route_hash:v5":            T_DECODE * TOPK,      # weights [T, TOPK]
    "x_norm_quant:v2":          T_DECODE * D,         # x_norm_i8 [T, D]
    # routed expert (RECV_MAX=64, RECV_TILE=16). i32 accumulators.
    "exp_gate_mm:v1":           N_LOCAL_EXPERTS * RECV_MAX * MOE_INTER,
    "exp_up_mm:v1":             N_LOCAL_EXPERTS * RECV_MAX * MOE_INTER,
    "exp_gate_up_act:v1":       16 * MOE_INTER,       # h_tile_fp32 [RECV_TILE, MOE_INTER]
    "exp_h_q:v2":               16,                   # h_tile_scale_dq [16, 1]
    "exp_h_q:v3":               16 * MOE_INTER,       # h_tile_i8 [16, MOE_INTER]
    "exp_w2_act:v3":            16 * D,               # recv_y_tile [16, D] bf16
    "exp_w2_mm:v1":             16 * D,               # y_i32 [16, D]
    # shared expert (single expert, T_PAD=16).
    "sh_gate_mm:v3":            T_PAD * MOE_INTER,    # gate_i32 [T_PAD, MOE_INTER]
    "sh_up_mm:v3":              T_PAD * MOE_INTER,    # up_i32 [T_PAD, MOE_INTER]
    "sh_gate_up_act_q:v2":      16 * MOE_INTER,       # h_tile_fp32 [16, MOE_INTER]
    "sh_gate_up_act_q:v7":      16 * 8,               # h_tile_scale_dq [16, SH_ROW_PAD=8]
    "sh_gate_up_act_q:v8":      16 * MOE_INTER,       # h_tile_i8 [16, MOE_INTER]
    "sh_w2_act:v2":             T_DECODE * D,         # sh [T, D] bf16
    "sh_w2_mm:v3":              16 * D,                # y_i32 [16, D]
}


def make_fp32(generator, count: int, *, scale: float = 0.05, positive: bool = False) -> np.ndarray:
    if positive:
        return generator.uniform(0.25, 1.5, size=count).astype(np.float32)
    return generator.uniform(-scale, scale, size=count).astype(np.float32)


def make_bf16(generator, count: int, *, scale: float = 0.05, positive: bool = False) -> np.ndarray:
    return float32_to_bf16(make_fp32(generator, count, scale=scale, positive=positive))


def make_i8(generator, count: int, *, scale: float = 1.0) -> np.ndarray:
    """Random int8 in [-127, 127], stored as int8 (kernel weight / activation).

    generator.integers(-127, 128) yields values in [-127, 127] inclusive; the
    int32->int8 cast is a no-op for that range (no overflow wrap)."""
    vals = generator.integers(-127, 128, size=count, dtype=np.int8)
    return vals


def _sigmoid(x):
    return np.reciprocal(np.float32(1.0) + np.exp(-x))


def _softplus_stable(x):
    """log1p(exp(-|x|)) + relu(x) = softplus, stable for large |x|."""
    return np.maximum(x, 0.0) + np.log1p(np.exp(-np.abs(x)))


def _int8_quant_per_row(x_f32):
    """Per-row symmetric INT8 quant matching the kernel's cast chain:
    round -> int32 -> fp16(round) -> int8(trunc). Returns (i8, scale_dequant[T,1])."""
    rows = x_f32.reshape(-1, x_f32.shape[-1])
    amax = np.max(np.abs(rows), axis=-1, keepdims=True)
    amax = np.maximum(amax, INT8_AMAX_EPS)
    scale_q = (np.float32(INT8_SCALE_MAX) / amax).astype(np.float32)
    scaled = rows * scale_q
    i32 = np.round(scaled).astype(np.int32)
    # kernel chain: i32 -> fp16(round) -> i8(trunc). numpy int32->int8 truncates,
    # matching the int8 result since fp16 round of a value already rounded to
    # int32 is a no-op for the |q| <= 127 range enforced by scale_q.
    i8 = i32.astype(np.int8)
    scale_dq = np.reciprocal(scale_q)
    return i8.reshape(x_f32.shape), scale_dq.reshape(*x_f32.shape[:-1], 1)


# ======================================================================================
# hc_pre family (rms / seed / linear sub-kernels; fused build_hc_pre_fused covers all)
# ======================================================================================
# The .pto hc_pre sub-kernels write into three shared intermediates (mixes_raw,
# inv_rms, post, comb, x_mixed) that the fused _hc_pre_separate computes
# end-to-end. Each sub-kernel test exercises only that stage's writes, so each
# build_ function generates the full fused golden and returns only the slice the
# sub-kernel is expected to produce. Where a sub-kernel only reads its inputs
# (e.g. hc_pre_seed writes zeros), the golden is the zero-filled output buffer.


def _hc_pre_fused_golden(x_fp32, hc_fn, hc_scale, hc_base, t_dim):
    """Compute the full hc_pre fused output (matches golden_hc_pre in hc_pre.py).

    Returns (x_mixed_bf16_uint16, post_fp32, comb_fp32, inv_rms_fp32, mixes_raw_fp32).
    """
    x_flat = x_fp32.reshape(t_dim, HC_DIM)
    # RMS: sum of squares over HC_DIM, rsqrt(+eps).
    sq_sum = np.zeros((t_dim, 1), dtype=np.float32)
    for k0 in range(0, HC_DIM, RMS_K_CHUNK):
        x_chunk = x_flat[:, k0:k0 + RMS_K_CHUNK]
        sq_sum += np.sum(x_chunk * x_chunk, axis=1, keepdims=True)
    inv_rms = np.reciprocal(np.sqrt(sq_sum * HC_DIM_INV + NORM_EPS))

    # Linear: split-K matmul x_flat @ hc_fn^T -> mixes_raw[T, MIX_HC].
    # Accumulate per-K-chunk partial dots then sum to match cube K-fragment order.
    n_chunk = HC_DIM // LINEAR_K_CHUNK
    x_k = x_flat.reshape(t_dim, 1, n_chunk, LINEAR_K_CHUNK)
    w_k = hc_fn.reshape(1, MIX_HC, n_chunk, LINEAR_K_CHUNK)
    per_chunk = np.sum(x_k * w_k, axis=3)            # [T, MIX_HC, n_chunk]
    mixes = np.zeros((t_dim, MIX_HC), dtype=np.float32)
    for c in range(n_chunk):
        mixes += per_chunk[:, :, c]
    mixes_raw = mixes.copy()                          # pre-inv_rms mixes
    mixes = mixes * inv_rms                           # post-inv_rms (gate inputs)

    pre = _sigmoid(mixes[:, :HC_MULT] * hc_scale[0] + hc_base[:HC_MULT]) + HC_EPS
    post_t = np.float32(2.0) * _sigmoid(
        mixes[:, HC_MULT:HC_MULT * 2] * hc_scale[1] + hc_base[HC_MULT:HC_MULT * 2]
    )
    comb_t = (mixes[:, HC_MULT * 2:] * hc_scale[2] + hc_base[HC_MULT * 2:]).reshape(
        t_dim, HC_MULT, HC_MULT
    )

    # softmax over last axis, then Sinkhorn (column-first, 20 iters).
    comb_t = _softmax_last_axis(comb_t) + HC_EPS
    comb_t = comb_t / (comb_t.sum(axis=-2, keepdims=True) + HC_EPS)
    for _ in range(HC_SINKHORN_ITER - 1):
        comb_t = comb_t / (comb_t.sum(axis=-1, keepdims=True) + HC_EPS)
        comb_t = comb_t / (comb_t.sum(axis=-2, keepdims=True) + HC_EPS)

    # mix_x: x_mixed = sum_h pre[:,h] * x[:,h,:]
    y0 = x_fp32[:, 0, :] * pre[:, 0:1]
    y1 = x_fp32[:, 1, :] * pre[:, 1:2]
    y2 = x_fp32[:, 2, :] * pre[:, 2:3]
    y3 = x_fp32[:, 3, :] * pre[:, 3:4]
    y = (y0 + y1) + (y2 + y3)
    x_mixed = float32_to_bf16(y.reshape(t_dim, D))
    return x_mixed, post_t, comb_t.reshape(t_dim, HC_MULT * HC_MULT), inv_rms, mixes_raw


def _softmax_last_axis(x):
    m = np.max(x, axis=-1, keepdims=True)
    e = np.exp(x - m)
    return e / np.sum(e, axis=-1, keepdims=True)


def _gen_hc_pre_inputs(generator, t_dim):
    """Random x, hc_fn, hc_scale, hc_base matching build_tensor_specs in hc_pre.py."""
    x = make_fp32(generator, t_dim * HC_MULT * D, scale=0.05).reshape(t_dim, HC_MULT, D)
    hc_fn = make_fp32(generator, MIX_HC * HC_DIM, scale=0.0519).reshape(MIX_HC, HC_DIM)
    hc_scale = np.array([0.076099, 0.032597, 0.226994], dtype=np.float32)
    hc_base = np.array([
        5.9166, -3.6223, -2.9324, -3.3124,
        -3.9100, -0.9384, -3.3256, -2.5240,
        2.0706, -2.5728, 0.1424, -3.9453,
        -3.8859, 3.4634, -3.3799, -2.6077,
        -2.7191, -2.4846, 2.0395, -0.5010,
        -3.5992, -2.7520, -3.3493, 3.1587,
    ], dtype=np.float32)
    return x, hc_fn, hc_scale, hc_base


def build_hc_pre_fused(meta, generator, ints):
    """Fused hc_pre reference (the full _hc_pre_separate math).

    The .pto has no single 'hc_pre_fused' sub-kernel (the fused syncall variant
    is device-specialized and skipped on sim); this builder is the canonical
    golden used by the sub-kernel builders below to derive their slices.
    """
    del ints
    t_dim = T_DECODE
    x, hc_fn, hc_scale, hc_base = _gen_hc_pre_inputs(generator, t_dim)
    x_mixed, post, comb, inv_rms, mixes_raw = _hc_pre_fused_golden(
        x, hc_fn, hc_scale, hc_base, t_dim
    )
    buffers = {
        "v1": x.reshape(-1),
        "v2": hc_fn.reshape(-1),
        "v3": hc_scale,
        "v4": hc_base,
    }
    golden = {
        "v5": x_mixed.reshape(-1),
        "v6": post.reshape(-1),
        "v7": comb.reshape(-1),
    }
    return buffers, golden


def build_hc_pre_rms(meta, generator, ints):
    """hc_pre_rms: v1=x[T,HC_DIM] fp32 (input), v2=inv_rms[T,1] fp32 (output).

    Computes the per-token rsqrt(mean(x^2)+eps). The .pto stores inv_rms in a
    transposed [T,1] dn-layout buffer; the golden is the flat [T,1] column so
    the compare covers every token's inv_rms.
    """
    del ints
    t_dim = T_DECODE
    x, _hc_fn, _hc_scale, _hc_base = _gen_hc_pre_inputs(generator, t_dim)
    x_flat = x.reshape(t_dim, HC_DIM)
    sq_sum = np.zeros((t_dim, 1), dtype=np.float32)
    for k0 in range(0, HC_DIM, RMS_K_CHUNK):
        x_chunk = x_flat[:, k0:k0 + RMS_K_CHUNK]
        sq_sum += np.sum(x_chunk * x_chunk, axis=1, keepdims=True)
    inv_rms = np.reciprocal(np.sqrt(sq_sum * HC_DIM_INV + NORM_EPS))
    buffers = {"v1": x_flat.reshape(-1), "v2": _flat_output(meta, "hc_pre_rms", "v2")}
    golden = {"v2": inv_rms.reshape(-1)}
    return buffers, golden


def build_hc_pre_seed(meta, generator, ints):
    """hc_pre_seed: v1=mixes_raw[t_linear, MIX_PAD] fp32 (output, zero-filled).

    The kernel writes zeros into the split-K atomic-add accumulator so the
    subsequent hc_pre_linear atomic-adds start from a clean state. Golden is
    the zero buffer of the parsed element count.
    """
    del ints
    zero_buf = _flat_output(meta, "hc_pre_seed", "v1")
    buffers = {"v1": zero_buf}
    golden = {"v1": np.zeros(zero_buf.size, dtype=np.float32)}
    return buffers, golden


def build_hc_pre_linear(meta, generator, ints):
    """hc_pre_linear: v1=x[T,HC_DIM], v2=hc_fn[MIX_HC,HC_DIM], v3=mixes_raw (output).

    Split-K matmul x @ hc_fn^T -> mixes_raw[T, MIX_HC], atomic-added from zero-seed.
    Golden returns the full mixes_raw (pre-inv_rms) so every spmd block's partial
    is covered.
    """
    del ints
    t_dim = T_DECODE
    x, hc_fn, _hc_scale, _hc_base = _gen_hc_pre_inputs(generator, t_dim)
    x_flat = x.reshape(t_dim, HC_DIM)
    # Per-K-chunk dot accumulation to match cube K-fragment order.
    n_chunk = HC_DIM // LINEAR_K_CHUNK
    x_k = x_flat.reshape(t_dim, 1, n_chunk, LINEAR_K_CHUNK)
    w_k = hc_fn.reshape(1, MIX_HC, n_chunk, LINEAR_K_CHUNK)
    per_chunk = np.sum(x_k * w_k, axis=3)
    mixes = np.zeros((t_dim, MIX_HC), dtype=np.float32)
    for c in range(n_chunk):
        mixes += per_chunk[:, :, c]
    buffers = {
        "v1": x_flat.reshape(-1),
        "v2": hc_fn.reshape(-1),
        "v3": _flat_output(meta, "hc_pre_linear", "v3"),
    }
    golden = {"v3": mixes.reshape(-1)}
    return buffers, golden


# ======================================================================================
# hc_post family
# ======================================================================================
def _gen_hc_post_inputs(generator, t_dim):
    """Random x, residual, post, comb matching build_tensor_specs in hc_post.py."""
    x = make_bf16(generator, t_dim * D, scale=0.05).reshape(t_dim, D)
    residual = make_fp32(generator, t_dim * HC_MULT * D, scale=0.05).reshape(t_dim, HC_MULT, D)
    post = np.float32(2.0) * _sigmoid(make_fp32(generator, t_dim * HC_MULT, scale=0.05).reshape(t_dim, HC_MULT))
    # comb: per-token row-stochastic [T, HC_MULT, HC_MULT].
    c_raw = generator.uniform(0.1, 1.1, size=(t_dim, HC_MULT, HC_MULT)).astype(np.float32)
    comb = c_raw / c_raw.sum(axis=-1, keepdims=True)
    return x, residual, post, comb


def _hc_post_core(x_bf16, residual, post, comb, t_dim):
    """Core hc_post math: y[:,out_h,:] = x*post[:,out_h] + sum_in_h residual[:,in_h,:]*comb[:,in_h,out_h]."""
    x = bf16_to_float32(x_bf16.reshape(-1, 1)).reshape(t_dim, D) if x_bf16.dtype == np.uint16 else x_bf16.astype(np.float32)
    comb3 = comb.reshape(t_dim, HC_MULT, HC_MULT)
    y = np.zeros((t_dim, HC_MULT, D), dtype=np.float32)
    for out_h in range(HC_MULT):
        y_row = x * post[:, out_h:out_h + 1]
        for in_h in range(HC_MULT):
            y_row = y_row + residual[:, in_h, :] * comb3[:, in_h, out_h:out_h + 1]
        y[:, out_h, :] = y_row
    return y


def build_hc_post(meta, generator, ints):
    """hc_post: v1=y(out), v2=post, v3=attn_out(bf16), v4=comb, v5=residual.

    y[t,out_h,:] = attn_out[t,:]*post[t,out_h] + sum_in_h residual[t,in_h,:]*comb[t,in_h,out_h].
    """
    del ints
    t_dim = T_DECODE
    x, residual, post, comb = _gen_hc_post_inputs(generator, t_dim)
    y = _hc_post_core(x, residual, post, comb, t_dim)
    buffers = {
        "v1": _flat_output(meta, "hc_post", "v1"),
        "v2": post.reshape(-1),
        "v3": x.reshape(-1),
        "v4": comb.reshape(-1),
        "v5": residual.reshape(-1),
    }
    golden = {"v1": y.reshape(-1)}
    return buffers, golden


def build_hc_post_inactive_pad(meta, generator, ints):
    """hc_post_inactive_pad: v1=y(out, zeroed for inactive rows).

    The kernel zero-fills the inactive tail of y. With num_tokens=0 (decode has
    no inactive rows when num_tokens==T), the whole y is the inactive region and
    the golden is the zero buffer. ints[0]=active_tokens (0 here), ints[2]=t_dim.
    """
    del ints
    zero_buf = _flat_output(meta, "hc_post_inactive_pad", "v1")
    buffers = {"v1": zero_buf}
    golden = {"v1": np.zeros(zero_buf.size, dtype=np.float32)}
    return buffers, golden


def build_hc_post_prefill(meta, generator, ints):
    """hc_post_prefill: v1=y(out), v2=post, v3=attn_out(bf16, 128 rows), v4=comb, v5=residual.

    Same math as hc_post but over a 128-token prefill tensor; the kernel pads
    the inactive tail (num_tokens..T) to zero. With num_tokens=T (=128) all rows
    are active.
    """
    num_tokens = ints[0] if len(ints) > 0 else 128
    t_dim = 128
    x, residual, post, comb = _gen_hc_post_inputs(generator, t_dim)
    y = _hc_post_core(x, residual, post, comb, t_dim)
    y[num_tokens:] = 0
    buffers = {
        "v1": _flat_output(meta, "hc_post_prefill", "v1"),
        "v2": post.reshape(-1),
        "v3": x.reshape(-1),
        "v4": comb.reshape(-1),
        "v5": residual.reshape(-1),
    }
    golden = {"v1": y.reshape(-1)}
    return buffers, golden


# ======================================================================================
# hc_head family (rms / seed / linear / pre_fused / reduce)
# ======================================================================================
def _gen_hc_head_inputs(generator, t_dim):
    """Random x_hc, hc_head_fn, scale, base matching build_tensor_specs in hc_head.py."""
    x_hc = make_fp32(generator, t_dim * HC_MULT * D, scale=0.05).reshape(t_dim, HC_MULT, D)
    hc_head_fn = make_fp32(generator, HC_MULT * HC_DIM, scale=0.0519).reshape(HC_MULT, HC_DIM)
    hc_head_scale = np.array([0.076099], dtype=np.float32)
    hc_head_base = np.array([5.9166, -3.6223, -2.9324, -3.3124], dtype=np.float32)
    return x_hc, hc_head_fn, hc_head_scale, hc_head_base


def _hc_head_rms_core(x_hc, t_dim):
    """inv_rms = rsqrt(mean(x_flat^2)+eps), x_flat=[T,HC_DIM]."""
    x_flat = x_hc.reshape(t_dim, HC_DIM)
    sq_sum = np.zeros((t_dim, 1), dtype=np.float32)
    for k0 in range(0, HC_DIM, HC_HEAD_RMS_K_CHUNK):
        x_chunk = x_flat[:, k0:k0 + HC_HEAD_RMS_K_CHUNK]
        sq_sum += np.sum(x_chunk * x_chunk, axis=1, keepdims=True)
    return np.reciprocal(np.sqrt(sq_sum * HC_DIM_INV + NORM_EPS))


def _hc_head_linear_core(x_hc, hc_head_fn, t_dim):
    """mixes = x_flat @ hc_head_fn^T, [T, HC_HEAD_PAD], per-K-chunk accumulation.

    Returns the padded [T, HC_HEAD_PAD] layout (HC_MULT=4 valid cols, rest 0)
    matching the .pto mixes_raw buffer's column width.
    """
    x_flat = x_hc.reshape(t_dim, HC_DIM)
    mixes = np.zeros((t_dim, HC_HEAD_PAD), dtype=np.float32)
    for h in range(HC_MULT):
        col = np.zeros((t_dim, 1), dtype=np.float32)
        for k0 in range(0, HC_DIM, HC_HEAD_LINEAR_K_CHUNK):
            x_chunk = x_flat[:, k0:k0 + HC_HEAD_LINEAR_K_CHUNK]
            w_chunk = hc_head_fn[h:h + 1, k0:k0 + HC_HEAD_LINEAR_K_CHUNK]
            col += np.sum(x_chunk * w_chunk, axis=1, keepdims=True)
        mixes[:, h:h + 1] = col
    return mixes


def build_hc_head_rms(meta, generator, ints):
    """hc_head_rms: v1=x[T,HC_DIM] fp32 (input), v2=inv_rms[T_MAX,1] fp32 (output).

    The .pto stores inv_rms in a [T_MAX=128, 1] buffer (padded for the head
    projection's T_MAX-shaped intermediates); the per-token inv_rms is valid for
    the first T_DECODE rows and zero-padded for the rest.
    """
    del ints
    t_dim = T_DECODE
    t_max = 128
    x_hc, _fn, _sc, _b = _gen_hc_head_inputs(generator, t_dim)
    inv_rms = _hc_head_rms_core(x_hc, t_dim)
    inv_rms_pad = np.zeros((t_max, 1), dtype=np.float32)
    inv_rms_pad[:t_dim] = inv_rms
    buffers = {"v1": x_hc.reshape(-1), "v2": _flat_output(meta, "hc_head_rms", "v2")}
    golden = {"v2": inv_rms_pad.reshape(-1)}
    return buffers, golden


def build_hc_head_seed(meta, generator, ints):
    """hc_head_seed: v1=mixes_raw[T_MAX, HC_HEAD_PAD] fp32 (output, zero-filled)."""
    del ints
    zero_buf = _flat_output(meta, "hc_head_seed", "v1")
    buffers = {"v1": zero_buf}
    golden = {"v1": np.zeros(zero_buf.size, dtype=np.float32)}
    return buffers, golden


def build_hc_head_linear(meta, generator, ints):
    """hc_head_linear: v1=x, v2=hc_head_fn[HC_MULT,HC_DIM], v3=mixes_raw[T_MAX, HC_HEAD_PAD] (output, atomic)."""
    del ints
    t_dim = T_DECODE
    t_max = 128
    x_hc, hc_head_fn, _sc, _b = _gen_hc_head_inputs(generator, t_dim)
    mixes = _hc_head_linear_core(x_hc, hc_head_fn, t_dim)
    mixes_pad = np.zeros((t_max, HC_HEAD_PAD), dtype=np.float32)
    mixes_pad[:t_dim] = mixes
    buffers = {
        "v1": x_hc.reshape(-1),
        "v2": hc_head_fn.reshape(-1),
        "v3": _flat_output(meta, "hc_head_linear", "v3"),
    }
    golden = {"v3": mixes_pad.reshape(-1)}
    return buffers, golden


def build_hc_head_pre_fused(meta, generator, ints):
    """hc_head_pre_fused: scale+sigmoid+transpose -> pre_t.

    v1=hc_head_scale[1], v2=hc_head_base[HC_MULT], v3=pre_t[HC_HEAD_PAD, T_MAX](out),
    v4=mixes_raw[T_MAX, HC_HEAD_PAD], v5=inv_rms[T_MAX,1].
    pre = sigmoid(mixes * inv_rms * scale + base) + HC_EPS, transposed into pre_t.
    """
    del ints
    t_dim = T_DECODE
    t_max = 128   # hc_head intermediates are padded to T_MAX
    x_hc, hc_head_fn, hc_head_scale, hc_head_base = _gen_hc_head_inputs(generator, t_dim)
    inv_rms = _hc_head_rms_core(x_hc, t_dim)
    mixes = _hc_head_linear_core(x_hc, hc_head_fn, t_dim)
    # pre operates on the HC_MULT valid columns of mixes (hc_head_base is [HC_MULT]).
    pre = _sigmoid(mixes[:, :HC_MULT] * inv_rms * hc_head_scale[0] + hc_head_base) + HC_EPS
    # Pad the input intermediates to T_MAX so v4/v5 match the .pto buffer sizes.
    mixes_pad = np.zeros((t_max, HC_HEAD_PAD), dtype=np.float32)
    mixes_pad[:t_dim] = mixes
    inv_rms_pad = np.zeros((t_max, 1), dtype=np.float32)
    inv_rms_pad[:t_dim] = inv_rms
    # pre_t is [HC_HEAD_PAD, T_MAX] with HC_MULT valid rows.
    pre_t = np.zeros((HC_HEAD_PAD, t_max), dtype=np.float32)
    pre_t[:HC_MULT, :t_dim] = pre.T
    buffers = {
        "v1": hc_head_scale.reshape(-1),
        "v2": hc_head_base.reshape(-1),
        "v3": _flat_output(meta, "hc_head_pre_fused", "v3"),
        "v4": mixes_pad.reshape(-1),
        "v5": inv_rms_pad.reshape(-1),
    }
    golden = {"v3": pre_t.reshape(-1)}
    return buffers, golden


def build_hc_head_reduce(meta, generator, ints):
    """hc_head_reduce: pre_t @ x_flat^T (per-head row-broadcast) -> y (bf16).

    v1=pre_t[HC_HEAD_PAD, T], v2=y[T,D] bf16 (out), v3=x[T,HC_DIM].
    y = sum_h x[:,h,:] * pre[:,h] (HC_MULT==4 hardcoded reduce).
    """
    del ints
    t_dim = T_DECODE
    x_hc, hc_head_fn, hc_head_scale, hc_head_base = _gen_hc_head_inputs(generator, t_dim)
    inv_rms = _hc_head_rms_core(x_hc, t_dim)
    mixes = _hc_head_linear_core(x_hc, hc_head_fn, t_dim)
    pre = _sigmoid(mixes[:, :HC_MULT] * inv_rms * hc_head_scale[0] + hc_head_base) + HC_EPS
    y0 = x_hc[:, 0, :] * pre[:, 0:1]
    y1 = x_hc[:, 1, :] * pre[:, 1:2]
    y2 = x_hc[:, 2, :] * pre[:, 2:3]
    y3 = x_hc[:, 3, :] * pre[:, 3:4]
    y = (y0 + y1) + (y2 + y3)
    t_max = 128
    pre_t = np.zeros((HC_HEAD_PAD, t_max), dtype=np.float32)
    pre_t[:HC_MULT, :t_dim] = pre.T
    buffers = {
        "v1": pre_t.reshape(-1),
        "v2": _flat_output(meta, "hc_head_reduce", "v2"),
        "v3": x_hc.reshape(-1),
    }
    golden = {"v2": float32_to_bf16(y.reshape(-1))}
    return buffers, golden


# ======================================================================================
# gate / MoE-router family
# ======================================================================================
def _gen_gate_inputs(generator, num_tokens=T_DECODE, layer_id=N_HASH_LAYERS):
    """Random x_mixed, norm_w, gate_w, gate_bias, tid2eid, input_ids matching
    build_tensor_specs in gate.py (decode T=8 active tokens).

    x_mixed is the [T_DECODE, D] bf16 activation entering the router. The
    router's padded intermediates (xg, inv_rms, xn_scale at [T_PAD, ...]) are
    produced by _ffn_norm_core padding the per-token computation to T_PAD.
    """
    x_mixed = float32_to_bf16(
        generator.standard_normal(T_DECODE * D).astype(np.float32)
    ).reshape(T_DECODE, D)
    norm_w = float32_to_bf16(np.ones(D, dtype=np.float32))
    gate_w = (generator.standard_normal(N_EXPERTS * D).astype(np.float32) / np.sqrt(D)).reshape(N_EXPERTS, D)
    gate_bias = (generator.standard_normal(N_EXPERTS).astype(np.float32) * 0.1)
    tid2eid = generator.integers(0, N_EXPERTS, size=(VOCAB, TOPK), dtype=np.int32)
    input_ids = generator.integers(0, VOCAB, size=(T_DECODE,), dtype=np.int64)
    return x_mixed, norm_w, gate_w, gate_bias, tid2eid, input_ids


def _ffn_norm_core(x_mixed_bf16, norm_w_bf16, num_tokens):
    """Deferred RMSNorm (qwen3-style): xg = bf16(x*gamma), inv_rms scalar folded
    downstream. Returns (xg[T_PAD,D], inv_rms[T_PAD,1], x_norm_i8[T_PAD,D],
    x_norm_scale[T_DECODE,1], scale_dq_g[T_PAD,1]).

    Inputs x_mixed/norm_w are [T_DECODE, D]; outputs are padded to T_PAD so they
    match the .pto's padded intermediate buffer sizes (xg, inv_rms, xn_scale at
    T_PAD=16 rows). x_norm_scale is [T_DECODE, 1] (the active-row output, which
    the kernel guards to active tokens).
    """
    x_f = bf16_to_float32(x_mixed_bf16.reshape(-1, 1)).reshape(T_DECODE, D) \
        if x_mixed_bf16.dtype == np.uint16 else x_mixed_bf16.astype(np.float32)
    nw = bf16_to_float32(norm_w_bf16.reshape(-1, 1)).reshape(D) \
        if norm_w_bf16.dtype == np.uint16 else norm_w_bf16.astype(np.float32)
    sq_sum = np.sum(x_f * x_f, axis=-1, keepdims=True).astype(np.float32)
    inv_rms_active = np.reciprocal(np.sqrt(sq_sum * (np.float32(1.0) / D) + NORM_EPS))
    xg_active = x_f * nw.reshape(1, D)
    # per-token symmetric INT8 quant of xg; inv_rms cancels in the int8 values.
    x_norm_i8_active, scale_dq_g_active = _int8_quant_per_row(xg_active)
    x_norm_scale = (scale_dq_g_active.reshape(T_DECODE, 1) * inv_rms_active)
    if num_tokens < T_DECODE:
        x_norm_scale[num_tokens:] = 0
    # Pad intermediates to T_PAD (the .pto xg/inv_rms/xn_scale buffer rows).
    xg = np.zeros((T_PAD, D), dtype=np.float32)
    xg[:T_DECODE] = xg_active
    inv_rms = np.zeros((T_PAD, 1), dtype=np.float32)
    inv_rms[:T_DECODE] = inv_rms_active
    x_norm_i8 = np.zeros((T_PAD, D), dtype=np.int8)
    x_norm_i8[:T_DECODE] = x_norm_i8_active
    scale_dq_g = np.zeros((T_PAD, 1), dtype=np.float32)
    scale_dq_g[:T_DECODE] = scale_dq_g_active
    return xg, inv_rms, x_norm_i8, x_norm_scale, scale_dq_g


def _gate_core(xg, inv_rms, gate_w, gate_bias):
    """sqrtsoftplus router score: logits = inv_rms * (xg @ gate_w^T);
    scores = sqrt(softplus(logits)); biased = scores + gate_bias."""
    logits = inv_rms * (xg @ gate_w.T)
    softplus = _softplus_stable(logits)
    scores = np.sqrt(softplus)
    biased = scores + gate_bias.reshape(1, -1)
    return scores, biased


def build_ffn_norm(meta, generator, ints):
    """ffn_norm: v1=x_mixed(bf16), v2=norm_w(bf16), v3=xg(out), v4=inv_rms(out),
    v5=x_norm_scale(out), v6=xn_scale(out).

    One token per core: deferred RMSNorm + amax + quant-scale. Outputs xg (not
    yet *inv_rms), inv_rms, x_norm_scale (= inv_rms * amax(xg)/127), xn_scale
    (= 127 / amax(xg)).
    """
    del ints
    x_mixed, norm_w, _gw, _gb, _t2e, _ids = _gen_gate_inputs(generator)
    xg, inv_rms, _x_norm_i8, x_norm_scale, scale_dq_g = _ffn_norm_core(x_mixed, norm_w, T_PAD)
    xn_scale = np.reciprocal(scale_dq_g)              # = 127 / amax(xg)
    buffers = {
        "v1": x_mixed.reshape(-1),
        "v2": norm_w.reshape(-1),
        "v3": _flat_output(meta, "ffn_norm", "v3"),
        "v4": _flat_output(meta, "ffn_norm", "v4"),
        "v5": _flat_output(meta, "ffn_norm", "v5"),
        "v6": _flat_output(meta, "ffn_norm", "v6"),
    }
    # v3=xg, v4=inv_rms, v5=x_norm_scale, v6=xn_scale (all [T,1 or D] flat).
    golden = {
        "v3": xg.reshape(-1),
        "v4": inv_rms.reshape(-1),
        "v5": x_norm_scale.reshape(-1),
        "v6": xn_scale.reshape(-1),
    }
    return buffers, golden


def build_gate(meta, generator, ints):
    """gate (gate_aic): v1=gate_bias, v2=xg, v3=gate_w, v4=inv_rms, v5=route_scores(out).

    Cube matmul xg @ gate_w^T -> logits; sqrtsoftplus -> scores; row-scale by
    inv_rms. Writes route_scores[T_PAD, SCORE_PAD] (N_EXPERTS valid cols, rest
    unused in this sub-kernel; gate_pre_route pads them -inf).
    """
    del ints
    x_mixed, norm_w, gate_w, gate_bias, _t2e, _ids = _gen_gate_inputs(generator)
    xg, inv_rms, _i8, _xns, _sd = _ffn_norm_core(x_mixed, norm_w, T_PAD)
    scores, _biased = _gate_core(xg, inv_rms, gate_w, gate_bias)
    # The .pto route_scores buffer is [T_PAD, SCORE_PAD]; fill valid cols with
    # scores, leave the pad tail at 0 (gate_pre_route will -inf it).
    route_scores = np.zeros((T_PAD, SCORE_PAD), dtype=np.float32)
    route_scores[:, :N_EXPERTS] = scores
    buffers = {
        "v1": gate_bias.reshape(-1),
        "v2": xg.reshape(-1),
        "v3": gate_w.reshape(-1),
        "v4": inv_rms.reshape(-1),
        "v5": _flat_output(meta, "gate", "v5"),
    }
    golden = {"v5": route_scores.reshape(-1)}
    return buffers, golden


def build_gate_pre_route(meta, generator, ints):
    """gate_pre_route: v1=biased_scores[T_PAD, SCORE_PAD] (output, init -inf pad).

    The kernel zeros inactive-token outputs and -inf-fills the biased_scores pad
    columns [N_EXPERTS:SCORE_PAD] so the sort ranks pad experts last. With no
    inactive tokens (num_tokens=T) the only write is the -inf pad tail.
    Golden = the full biased_scores with the -inf pad tail (valid cols left at
    whatever the input was; we generate them as the post-gate biased scores for a
    self-contained check).
    """
    del ints
    x_mixed, norm_w, gate_w, gate_bias, _t2e, _ids = _gen_gate_inputs(generator)
    xg, inv_rms, _i8, _xns, _sd = _ffn_norm_core(x_mixed, norm_w, T_PAD)
    _scores, biased = _gate_core(xg, inv_rms, gate_w, gate_bias)
    biased_scores = np.zeros((T_PAD, SCORE_PAD), dtype=np.float32)
    biased_scores[:, :N_EXPERTS] = biased
    biased_scores[:, N_EXPERTS:] = FP32_NEG_INF
    buffers = {"v1": _flat_output(meta, "gate_pre_route", "v1")}
    golden = {"v1": biased_scores.reshape(-1)}
    return buffers, golden


def build_route_hash(meta, generator, ints):
    """route_hash: v1=input_ids, v2=tid2eid, v3=route_scores, v4=indices(out),
    v5=weights(out).

    Hash layers (layer_id < N_HASH_LAYERS): indices = tid2eid[input_ids];
    weights = gather(scores, indices) / sum * ROUTE_SCALE.
    """
    del ints
    x_mixed, norm_w, gate_w, gate_bias, tid2eid, input_ids = _gen_gate_inputs(generator, layer_id=0)
    xg, inv_rms, _i8, _xns, _sd = _ffn_norm_core(x_mixed, norm_w, T_PAD)
    scores, _biased = _gate_core(xg, inv_rms, gate_w, gate_bias)
    indices = tid2eid[input_ids[:T_DECODE]]            # [T, TOPK]
    topk_vals = np.take_along_axis(scores[:T_DECODE], indices.astype(np.int64), axis=1)
    denom = topk_vals.sum(axis=-1, keepdims=True)
    weights = (topk_vals / denom) * ROUTE_SCALE
    # route_scores buffer is [T_PAD, SCORE_PAD]; pad tail 0.
    route_scores = np.zeros((T_PAD, SCORE_PAD), dtype=np.float32)
    route_scores[:, :N_EXPERTS] = scores
    buffers = {
        "v1": input_ids[:T_DECODE].reshape(-1),
        "v2": tid2eid.reshape(-1),
        "v3": route_scores.reshape(-1),
        "v4": _flat_output(meta, "route_hash", "v4"),
        "v5": _flat_output(meta, "route_hash", "v5"),
    }
    golden = {
        "v4": indices.astype(np.int32).reshape(-1),
        "v5": weights.astype(np.float32).reshape(-1),
    }
    return buffers, golden


def build_x_norm_quant(meta, generator, ints):
    """x_norm_quant: v1=xn_scale[T_PAD,1], v2=x_norm_i8[T,D] (out), v3=xg[T,D].

    Per-token symmetric INT8 quant of xg using the precomputed xn_scale
    (= 127 / amax(xg)) from ffn_norm. inv_rms cancels in the int8 values.
    """
    del ints
    x_mixed, norm_w, _gw, _gb, _t2e, _ids = _gen_gate_inputs(generator)
    xg, _inv_rms, x_norm_i8, _xns, scale_dq_g = _ffn_norm_core(x_mixed, norm_w, T_PAD)
    xn_scale = np.reciprocal(scale_dq_g).reshape(T_PAD, 1)
    buffers = {
        "v1": xn_scale.reshape(-1),
        "v2": _flat_output(meta, "x_norm_quant", "v2"),
        "v3": xg.reshape(-1),
    }
    golden = {"v2": x_norm_i8[:T_DECODE].reshape(-1)}
    return buffers, golden


# ======================================================================================
# Routed expert (exp_*) family -- INT8 x INT8 -> INT32 cube matmuls, dequant AFTER.
# ======================================================================================
def _gen_routed_inputs(generator):
    """Random recv_x(i8), recv_scale_dq, recv_weights, routed_wN(i8)+scale matching
    build_tensor_specs in expert_routed.py. Weights are plain random int8 (the
    golden is a pure int32 matmul so the weight distribution does not matter for
    correctness; the model's gen_routed_weight grid sim is a perf/realism
    concern, not a precision-test concern)."""
    recv_x = make_i8(generator, N_LOCAL_EXPERTS * RECV_MAX * D).reshape(N_LOCAL_EXPERTS, RECV_MAX, D)
    recv_scale_dq = make_fp32(generator, N_LOCAL_EXPERTS * RECV_MAX, scale=0.05).reshape(N_LOCAL_EXPERTS, RECV_MAX)
    recv_weights = generator.uniform(0.0, 1.0, size=(N_LOCAL_EXPERTS, RECV_MAX)).astype(np.float32)
    routed_w1 = make_i8(generator, N_LOCAL_EXPERTS * MOE_INTER * D).reshape(N_LOCAL_EXPERTS, MOE_INTER, D)
    routed_w1_scale = make_fp32(generator, N_LOCAL_EXPERTS * MOE_INTER, scale=0.05).reshape(N_LOCAL_EXPERTS, MOE_INTER)
    routed_w3 = make_i8(generator, N_LOCAL_EXPERTS * MOE_INTER * D).reshape(N_LOCAL_EXPERTS, MOE_INTER, D)
    routed_w3_scale = make_fp32(generator, N_LOCAL_EXPERTS * MOE_INTER, scale=0.05).reshape(N_LOCAL_EXPERTS, MOE_INTER)
    routed_w2 = make_i8(generator, N_LOCAL_EXPERTS * D * MOE_INTER).reshape(N_LOCAL_EXPERTS, D, MOE_INTER)
    routed_w2_scale = make_fp32(generator, N_LOCAL_EXPERTS * D, scale=0.05).reshape(N_LOCAL_EXPERTS, D)
    return (recv_x, recv_scale_dq, recv_weights,
            routed_w1, routed_w1_scale, routed_w3, routed_w3_scale,
            routed_w2, routed_w2_scale)


def build_exp_gate_mm(meta, generator, ints):
    """exp_gate_mm: v1=gate_e(out, i32), v2=recv_x(i8), v3=routed_w1(i8).

    INT8 x INT8 -> INT32 cube matmul: gate_e[RECV_MAX, MOE_INTER] = recv_x @ w1^T.
    Local-expert axis is flattened: v1 is [N_LOCAL_EXPERTS*RECV_MAX, MOE_INTER].
    """
    del ints
    (recv_x, _rsd, _rw, routed_w1, _w1s, _w3, _w3s, _w2, _w2s) = _gen_routed_inputs(generator)
    gate_e = np.zeros((N_LOCAL_EXPERTS * RECV_MAX, MOE_INTER), dtype=np.int32)
    for e in range(N_LOCAL_EXPERTS):
        gate_e[e * RECV_MAX:(e + 1) * RECV_MAX] = (
            recv_x[e].astype(np.int32) @ routed_w1[e].astype(np.int32).T
        )
    buffers = {
        "v1": _flat_output(meta, "exp_gate_mm", "v1"),
        "v2": recv_x.reshape(-1),
        "v3": routed_w1.reshape(-1),
    }
    golden = {"v1": gate_e.reshape(-1)}
    return buffers, golden


def build_exp_up_mm(meta, generator, ints):
    """exp_up_mm: v1=up_e(out, i32), v2=recv_x(i8), v3=routed_w3(i8).

    Same as exp_gate_mm but with w3. v1 is [N_LOCAL_EXPERTS*RECV_MAX, MOE_INTER].
    """
    del ints
    (recv_x, _rsd, _rw, _w1, _w1s, routed_w3, _w3s, _w2, _w2s) = _gen_routed_inputs(generator)
    up_e = np.zeros((N_LOCAL_EXPERTS * RECV_MAX, MOE_INTER), dtype=np.int32)
    for e in range(N_LOCAL_EXPERTS):
        up_e[e * RECV_MAX:(e + 1) * RECV_MAX] = (
            recv_x[e].astype(np.int32) @ routed_w3[e].astype(np.int32).T
        )
    buffers = {
        "v1": _flat_output(meta, "exp_up_mm", "v1"),
        "v2": recv_x.reshape(-1),
        "v3": routed_w3.reshape(-1),
    }
    golden = {"v1": up_e.reshape(-1)}
    return buffers, golden


def _exp_gate_up_act_core(gate_i32, up_i32, recv_scale_dq, w1_scale, w2_scale_w3):
    """SwiGLU activation: gate*sigmoid(gate)*up, dequantized by per-row x scale x
    per-channel w scale; clamped to SWIGLU_LIMIT. Returns h_fp32[RECV_MAX, MOE_INTER].

    w2_scale_w3 is routed_w3_scale (per the kernel's up dequant path).
    """
    gate = gate_i32.astype(np.float32) * recv_scale_dq[:, None] * w1_scale[None, :]
    up = up_i32.astype(np.float32) * recv_scale_dq[:, None] * w2_scale_w3[None, :]
    if SWIGLU_LIMIT > 0:
        gate = np.minimum(gate, SWIGLU_LIMIT)
        up = np.maximum(np.minimum(up, SWIGLU_LIMIT), -SWIGLU_LIMIT)
    silu = gate * _sigmoid(gate)
    return silu * up


def build_exp_gate_up_act(meta, generator, ints):
    """exp_gate_up_act: v1=h_tile_fp32(out), v2=gate_slab(i32), v3=up_slab(i32),
    v4=recv_scale_dq, v5=routed_w1_scale, v6=routed_w3_scale.

    SwiGLU on one (expert, row-tile) slab: h = silu(gate)*up, dequantized.
    The .pto v1 is [16, MOE_INTER] (one RECV_TILE=16 row-tile of one expert).
    """
    del ints
    (recv_x, recv_scale_dq, _rw, _w1, w1_scale, _w3, w3_scale, _w2, _w2s) = _gen_routed_inputs(generator)
    # Build full gate/up i32 slabs then take the first expert's first RECV_TILE.
    gate_e_full = recv_x[0].astype(np.int32) @ _w1[0].astype(np.int32).T  # [RECV_MAX, MOE_INTER]
    up_e_full = recv_x[0].astype(np.int32) @ _w3[0].astype(np.int32).T
    h_full = _exp_gate_up_act_core(
        gate_e_full, up_e_full, recv_scale_dq[0], w1_scale[0], w3_scale[0]
    )
    h_tile = h_full[:16]  # RECV_TILE = 16
    buffers = {
        "v1": _flat_output(meta, "exp_gate_up_act", "v1"),
        "v2": gate_e_full.reshape(-1),
        "v3": up_e_full.reshape(-1),
        "v4": recv_scale_dq.reshape(-1),
        "v5": w1_scale.reshape(-1),
        "v6": w3_scale.reshape(-1),
    }
    golden = {"v1": h_tile.reshape(-1)}
    return buffers, golden


def build_exp_h_q(meta, generator, ints):
    """exp_h_q: v1=h_tile_fp32[16, MOE_INTER], v2=h_tile_scale_dq(out, [16,1]),
    v3=h_tile_i8(out, [16, MOE_INTER]).

    Per-row symmetric INT8 requant of the activation h. h_tile_scale_dq =
    1 / (127 / amax(h_row)) = amax(h_row) / 127.
    """
    del ints
    # Rebuild h from fresh random i8 weights to keep the test self-contained.
    (recv_x, recv_scale_dq, _rw, routed_w1, w1_scale, routed_w3, w3_scale, _w2, _w2s) = _gen_routed_inputs(generator)
    gate_e = recv_x[0].astype(np.int32) @ routed_w1[0].astype(np.int32).T
    up_e = recv_x[0].astype(np.int32) @ routed_w3[0].astype(np.int32).T
    h_full = _exp_gate_up_act_core(
        gate_e, up_e, recv_scale_dq[0], w1_scale[0], w3_scale[0]
    )
    h_tile = h_full[:16]                                  # [16, MOE_INTER]
    h_i8, h_sd = _int8_quant_per_row(h_tile)              # h_sd = [16, 1]
    buffers = {
        "v1": h_tile.reshape(-1),
        "v2": _flat_output(meta, "exp_h_q", "v2"),
        "v3": _flat_output(meta, "exp_h_q", "v3"),
    }
    golden = {
        "v2": h_sd.reshape(-1),
        "v3": h_i8.reshape(-1),
    }
    return buffers, golden


def build_exp_w2_mm(meta, generator, ints):
    """exp_w2_mm: v1=y_i32(out, [16, D]), v2=h_tile_i8, v3=routed_w2(i8).

    INT8 x INT8 -> INT32 cube matmul: y_i32 = h_tile_i8 @ routed_w2^T.
    """
    del ints
    (recv_x, recv_scale_dq, _rw, routed_w1, w1_scale, routed_w3, w3_scale, routed_w2, _w2s) = _gen_routed_inputs(generator)
    gate_e = recv_x[0].astype(np.int32) @ routed_w1[0].astype(np.int32).T
    up_e = recv_x[0].astype(np.int32) @ routed_w3[0].astype(np.int32).T
    h_full = _exp_gate_up_act_core(
        gate_e, up_e, recv_scale_dq[0], w1_scale[0], w3_scale[0]
    )
    h_tile = h_full[:16]
    h_i8, _h_sd = _int8_quant_per_row(h_tile)
    y_i32 = h_i8.astype(np.int32) @ routed_w2[0].astype(np.int32).T   # [16, D]
    buffers = {
        "v1": _flat_output(meta, "exp_w2_mm", "v1"),
        "v2": h_i8.reshape(-1),
        "v3": routed_w2.reshape(-1),
    }
    golden = {"v1": y_i32.reshape(-1)}
    return buffers, golden


def build_exp_w2_act(meta, generator, ints):
    """exp_w2_act: v1=recv_weights, v2=h_tile_scale_dq, v3=recv_y_tile(out, bf16),
    v4=y_i32, v5=routed_w2_scale.

    Dequant w2 output: recv_y = y_i32 * (h_scale * recv_weight) * w2_scale, cast bf16.
    """
    del ints
    (recv_x, recv_scale_dq, recv_weights, routed_w1, w1_scale, routed_w3, w3_scale, routed_w2, w2_scale) = _gen_routed_inputs(generator)
    gate_e = recv_x[0].astype(np.int32) @ routed_w1[0].astype(np.int32).T
    up_e = recv_x[0].astype(np.int32) @ routed_w3[0].astype(np.int32).T
    h_full = _exp_gate_up_act_core(
        gate_e, up_e, recv_scale_dq[0], w1_scale[0], w3_scale[0]
    )
    h_tile = h_full[:16]
    h_i8, h_sd = _int8_quant_per_row(h_tile)
    y_i32 = h_i8.astype(np.int32) @ routed_w2[0].astype(np.int32).T
    # row_scale_blk = h_sd * recv_weight (per-row, broadcast over D).
    w_per_row = recv_weights[0, :16].reshape(16, 1)
    row_scale = h_sd * w_per_row
    recv_y = y_i32.astype(np.float32) * row_scale * w2_scale[0][None, :]
    buffers = {
        "v1": recv_weights.reshape(-1),
        "v2": h_sd.reshape(-1),
        "v3": _flat_output(meta, "exp_w2_act", "v3"),
        "v4": y_i32.reshape(-1),
        "v5": w2_scale.reshape(-1),
    }
    golden = {"v3": float32_to_bf16(recv_y.reshape(-1))}
    return buffers, golden


# ======================================================================================
# Shared expert (sh_*) family -- same INT8 x INT8 -> INT32 math, single expert (no E axis).
# ======================================================================================
def _gen_shared_inputs(generator):
    """Random x_local_i8, x_local_scale_dq, shared_wN(i8)+scale matching
    build_tensor_specs in expert_shared.py."""
    x_local_i8 = make_i8(generator, T_DECODE * D).reshape(T_DECODE, D)
    x_local_scale_dq = make_fp32(generator, T_DECODE, scale=0.05).reshape(T_DECODE, 1)
    shared_w1 = make_i8(generator, MOE_INTER * D).reshape(MOE_INTER, D)
    shared_w1_scale = make_fp32(generator, MOE_INTER, scale=0.05)
    shared_w3 = make_i8(generator, MOE_INTER * D).reshape(MOE_INTER, D)
    shared_w3_scale = make_fp32(generator, MOE_INTER, scale=0.05)
    shared_w2 = make_i8(generator, D * MOE_INTER).reshape(D, MOE_INTER)
    shared_w2_scale = make_fp32(generator, D, scale=0.05)
    return (x_local_i8, x_local_scale_dq,
            shared_w1, shared_w1_scale, shared_w3, shared_w3_scale,
            shared_w2, shared_w2_scale)


def build_sh_gate_mm(meta, generator, ints):
    """sh_gate_mm: v1=x_local_i8[T,D], v2=shared_w1[MOE_INTER,D], v3=gate_i32(out, [T_PAD, MOE_INTER]).

    INT8 x INT8 -> INT32 matmul: gate_i32 = x_local_i8 @ shared_w1^T. Padded to T_PAD rows.
    """
    del ints
    (x_i8, _xsd, sw1, _sw1s, _sw3, _sw3s, _sw2, _sw2s) = _gen_shared_inputs(generator)
    gate_i32 = x_i8.astype(np.int32) @ sw1.astype(np.int32).T   # [T_DECODE, MOE_INTER]
    gate_pad = np.zeros((T_PAD, MOE_INTER), dtype=np.int32)
    gate_pad[:T_DECODE] = gate_i32
    buffers = {
        "v1": x_i8.reshape(-1),
        "v2": sw1.reshape(-1),
        "v3": _flat_output(meta, "sh_gate_mm", "v3"),
    }
    golden = {"v3": gate_pad.reshape(-1)}
    return buffers, golden


def build_sh_up_mm(meta, generator, ints):
    """sh_up_mm: v1=x_local_i8, v2=shared_w3, v3=up_i32(out, [T_PAD, MOE_INTER])."""
    del ints
    (x_i8, _xsd, _sw1, _sw1s, sw3, _sw3s, _sw2, _sw2s) = _gen_shared_inputs(generator)
    up_i32 = x_i8.astype(np.int32) @ sw3.astype(np.int32).T
    up_pad = np.zeros((T_PAD, MOE_INTER), dtype=np.int32)
    up_pad[:T_DECODE] = up_i32
    buffers = {
        "v1": x_i8.reshape(-1),
        "v2": sw3.reshape(-1),
        "v3": _flat_output(meta, "sh_up_mm", "v3"),
    }
    golden = {"v3": up_pad.reshape(-1)}
    return buffers, golden


def _sh_gate_up_act_core(gate_i32, up_i32, x_scale_dq, w1_scale, w3_scale):
    """Shared SwiGLU: sh_h = silu(gate)*up, dequantized by per-row x scale x per-channel w scale."""
    gate = gate_i32.astype(np.float32) * x_scale_dq * w1_scale[None, :]
    up = up_i32.astype(np.float32) * x_scale_dq * w3_scale[None, :]
    if SWIGLU_LIMIT > 0:
        gate = np.minimum(gate, SWIGLU_LIMIT)
        up = np.maximum(np.minimum(up, SWIGLU_LIMIT), -SWIGLU_LIMIT)
    silu = gate * _sigmoid(gate)
    return silu * up


def build_sh_gate_up_act_q(meta, generator, ints):
    """sh_gate_up_act_q: fused SwiGLU + per-row INT8 requant.

    v1=x_local_scale_dq[T,1], v2=h_tile_fp32(out, [16, MOE_INTER]),
    v3=gate_i32[16, MOE_INTER], v4=up_i32[16, MOE_INTER], v5=shared_w1_scale,
    v6=shared_w3_scale, v7=h_tile_scale_dq(out, [16, 8]), v8=h_tile_i8(out, [16, MOE_INTER]).

    Computes h = silu(gate)*up (dequant), then per-row INT8 requant of h into
    h_tile_i8 + h_tile_scale_dq.
    """
    del ints
    (x_i8, x_sd, sw1, sw1s, sw3, sw3s, _sw2, _sw2s) = _gen_shared_inputs(generator)
    gate_i32 = x_i8.astype(np.int32) @ sw1.astype(np.int32).T
    up_i32 = x_i8.astype(np.int32) @ sw3.astype(np.int32).T
    h_full = _sh_gate_up_act_core(gate_i32, up_i32, x_sd, sw1s, sw3s)  # [T_DECODE, MOE_INTER]
    h_tile = np.zeros((T_PAD, MOE_INTER), dtype=np.float32)
    h_tile[:T_DECODE] = h_full
    h_i8, h_sd = _int8_quant_per_row(h_tile)        # h_sd = [16, 1]
    # h_tile_scale_dq buffer is [16, SH_ROW_PAD=8]; fill col 0 with h_sd.
    h_scale_dq_pad = np.zeros((T_PAD, 8), dtype=np.float32)
    h_scale_dq_pad[:, 0:1] = h_sd
    buffers = {
        "v1": x_sd.reshape(-1),
        "v2": _flat_output(meta, "sh_gate_up_act_q", "v2"),
        "v3": gate_i32.reshape(-1),
        "v4": up_i32.reshape(-1),
        "v5": sw1s.reshape(-1),
        "v6": sw3s.reshape(-1),
        "v7": _flat_output(meta, "sh_gate_up_act_q", "v7"),
        "v8": _flat_output(meta, "sh_gate_up_act_q", "v8"),
    }
    golden = {
        "v2": h_tile.reshape(-1),
        "v7": h_scale_dq_pad.reshape(-1),
        "v8": h_i8.reshape(-1),
    }
    return buffers, golden


def build_sh_w2_mm(meta, generator, ints):
    """sh_w2_mm: v1=h_tile_i8[16, MOE_INTER], v2=shared_w2[D, MOE_INTER], v3=y_i32(out, [16, D]).

    INT8 x INT8 -> INT32 cube matmul: y_i32 = h_tile_i8 @ shared_w2^T.
    """
    del ints
    (x_i8, x_sd, sw1, sw1s, sw3, sw3s, sw2, _sw2s) = _gen_shared_inputs(generator)
    gate_i32 = x_i8.astype(np.int32) @ sw1.astype(np.int32).T
    up_i32 = x_i8.astype(np.int32) @ sw3.astype(np.int32).T
    h_full = _sh_gate_up_act_core(gate_i32, up_i32, x_sd, sw1s, sw3s)
    h_tile = np.zeros((T_PAD, MOE_INTER), dtype=np.float32)
    h_tile[:T_DECODE] = h_full
    h_i8, _h_sd = _int8_quant_per_row(h_tile)
    y_i32 = h_i8.astype(np.int32) @ sw2.astype(np.int32).T   # [16, D]
    buffers = {
        "v1": h_i8.reshape(-1),
        "v2": sw2.reshape(-1),
        "v3": _flat_output(meta, "sh_w2_mm", "v3"),
    }
    golden = {"v3": y_i32.reshape(-1)}
    return buffers, golden


def build_sh_w2_act(meta, generator, ints):
    """sh_w2_act: v1=h_tile_scale_dq[16,8], v2=sh(out, bf16, [T,D]), v3=y_i32[16,D],
    v4=shared_w2_scale[D].

    Dequant w2 output: sh = y_i32 * max(h_scale_dq_row) * w2_scale, cast bf16.
    The kernel takes a row-max over the [16,8] h_tile_scale_dq (only col 0 valid)
    before applying it; we mirror that with np.max over axis=1.
    """
    del ints
    (x_i8, x_sd, sw1, sw1s, sw3, sw3s, sw2, sw2s) = _gen_shared_inputs(generator)
    gate_i32 = x_i8.astype(np.int32) @ sw1.astype(np.int32).T
    up_i32 = x_i8.astype(np.int32) @ sw3.astype(np.int32).T
    h_full = _sh_gate_up_act_core(gate_i32, up_i32, x_sd, sw1s, sw3s)
    h_tile = np.zeros((T_PAD, MOE_INTER), dtype=np.float32)
    h_tile[:T_DECODE] = h_full
    h_i8, h_sd = _int8_quant_per_row(h_tile)
    h_scale_dq_pad = np.zeros((T_PAD, 8), dtype=np.float32)
    h_scale_dq_pad[:, 0:1] = h_sd
    y_i32 = h_i8.astype(np.int32) @ sw2.astype(np.int32).T
    # row-max of h_tile_scale_dq (col 0 is the only valid col -> max == h_sd).
    h_scale_row = np.max(h_scale_dq_pad, axis=1, keepdims=True)   # [16, 1]
    sh = y_i32.astype(np.float32) * h_scale_row * sw2s[None, :]
    # sh output is [T_DECODE, D] (valid rows); pad rows T_DECODE..T_PAD stay 0.
    sh_out = np.zeros((T_DECODE, D), dtype=np.float32)
    sh_out[:T_DECODE] = sh[:T_DECODE]
    buffers = {
        "v1": h_scale_dq_pad.reshape(-1),
        "v2": _flat_output(meta, "sh_w2_act", "v2"),
        "v3": y_i32.reshape(-1),
        "v4": sw2s.reshape(-1),
    }
    golden = {"v2": float32_to_bf16(sh_out.reshape(-1))}
    return buffers, golden


# ======================================================================================
# BUILDERS registry -- maps the .pto kernel name to its build_ function.
# ======================================================================================
BUILDERS = {
    "hc_pre_fused":          build_hc_pre_fused,
    "hc_pre_linear":         build_hc_pre_linear,
    "hc_pre_rms":            build_hc_pre_rms,
    "hc_pre_seed":           build_hc_pre_seed,
    "hc_post":               build_hc_post,
    "hc_post_inactive_pad":  build_hc_post_inactive_pad,
    "hc_post_prefill":       build_hc_post_prefill,
    "hc_head_linear":        build_hc_head_linear,
    "hc_head_pre_fused":     build_hc_head_pre_fused,
    "hc_head_reduce":        build_hc_head_reduce,
    "hc_head_rms":           build_hc_head_rms,
    "hc_head_seed":          build_hc_head_seed,
    "ffn_norm":              build_ffn_norm,
    "gate":                  build_gate,
    "gate_pre_route":        build_gate_pre_route,
    "route_hash":            build_route_hash,
    "x_norm_quant":          build_x_norm_quant,
    "exp_gate_mm":           build_exp_gate_mm,
    "exp_gate_up_act":       build_exp_gate_up_act,
    "exp_h_q":               build_exp_h_q,
    "exp_up_mm":             build_exp_up_mm,
    "exp_w2_act":            build_exp_w2_act,
    "exp_w2_mm":             build_exp_w2_mm,
    "sh_gate_mm":            build_sh_gate_mm,
    "sh_gate_up_act_q":      build_sh_gate_up_act_q,
    "sh_up_mm":              build_sh_up_mm,
    "sh_w2_act":             build_sh_w2_act,
    "sh_w2_mm":              build_sh_w2_mm,
}


def _build_legacy_name_map(meta):
    ordered = list(meta.read_order)
    return {f'v{idx}': name for idx, name in enumerate(ordered, start=1)}


def _rewrite_legacy_buffer_names(entries, legacy_to_actual):
    rewritten = {}
    for name, value in entries.items():
        rewritten[legacy_to_actual.get(name, name)] = value
    return rewritten


def run_case(case_name: str):
    """Generate inputs + golden for one kernel and write them to *.bin / golden_*.bin.

    Mirrors the qwen3_decode_golden_lib.run_case contract: the harness (vpto_run.py
    --golden-lib) calls this after cd-ing into the per-kernel run dir, which
    contains main.cpp (parsed by load_case_meta) + outputs.txt.
    """
    from dataclasses import replace
    from validation_runtime import load_case_meta, load_int32_assignments
    meta = load_case_meta()
    legacy_to_actual = _build_legacy_name_map(meta)
    # Alias v1..vN -> actual buffer names so elem_counts/np_types resolve under
    # the legacy naming the build_ functions use.
    elem_counts = dict(meta.elem_counts)
    np_types = dict(meta.np_types)
    for legacy, actual in legacy_to_actual.items():
        if legacy in elem_counts:
            continue
        if actual not in elem_counts or actual not in np_types:
            continue
        elem_counts[legacy] = elem_counts[actual]
        np_types[legacy] = np_types[actual]
    meta = replace(meta, elem_counts=elem_counts, np_types=np_types)
    generator = rng()
    ints = load_int32_assignments()
    buffers, golden = BUILDERS[case_name](meta, generator, ints)
    buffers = _rewrite_legacy_buffer_names(buffers, legacy_to_actual)
    golden = _rewrite_legacy_buffer_names(golden, legacy_to_actual)
    write_buffers(meta, buffers)
    write_golden(meta, golden)
